version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: adminedal/jeevini-php:prod

  # webserver:
  #   image: nginx:alpine
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
  #   restart: unless-stopped
  #   ports: 
  #     - '8080:80'

  # db:
  #   image: mysql:5.7.22
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: random
