<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    public function insertStates (){

    $states = array (
        'states' => 
        
          array (
            'state' => 'Andhra Pradesh',
            'districts' => 
            array (
              0 => 'Anantapur',
              1 => 'Chittoor',
              2 => 'East Godavari',
              3 => 'Guntur',
              4 => 'Krishna',
              5 => 'Kurnool',
              6 => 'Nellore',
              7 => 'Prakasam',
              8 => 'Srikakulam',
              9 => 'Visakhapatnam',
              10 => 'Vizianagaram',
              11 => 'West Godavari',
              12 => 'YSR Kadapa',
            ),
          ),
          1 => 
          array (
            'state' => 'Arunachal Pradesh',
            'districts' => 
            array (
              0 => 'Tawang',
              1 => 'West Kameng',
              2 => 'East Kameng',
              3 => 'Papum Pare',
              4 => 'Kurung Kumey',
              5 => 'Kra Daadi',
              6 => 'Lower Subansiri',
              7 => 'Upper Subansiri',
              8 => 'West Siang',
              9 => 'East Siang',
              10 => 'Siang',
              11 => 'Upper Siang',
              12 => 'Lower Siang',
              13 => 'Lower Dibang Valley',
              14 => 'Dibang Valley',
              15 => 'Anjaw',
              16 => 'Lohit',
              17 => 'Namsai',
              18 => 'Changlang',
              19 => 'Tirap',
              20 => 'Longding',
            ),
          ),
          2 => 
          array (
            'state' => 'Assam',
            'districts' => 
            array (
              0 => 'Baksa',
              1 => 'Barpeta',
              2 => 'Biswanath',
              3 => 'Bongaigaon',
              4 => 'Cachar',
              5 => 'Charaideo',
              6 => 'Chirang',
              7 => 'Darrang',
              8 => 'Dhemaji',
              9 => 'Dhubri',
              10 => 'Dibrugarh',
              11 => 'Goalpara',
              12 => 'Golaghat',
              13 => 'Hailakandi',
              14 => 'Hojai',
              15 => 'Jorhat',
              16 => 'Kamrup Metropolitan',
              17 => 'Kamrup',
              18 => 'Karbi Anglong',
              19 => 'Karimganj',
              20 => 'Kokrajhar',
              21 => 'Lakhimpur',
              22 => 'Majuli',
              23 => 'Morigaon',
              24 => 'Nagaon',
              25 => 'Nalbari',
              26 => 'Dima Hasao',
              27 => 'Sivasagar',
              28 => 'Sonitpur',
              29 => 'South Salmara-Mankachar',
              30 => 'Tinsukia',
              31 => 'Udalguri',
              32 => 'West Karbi Anglong',
            ),
          ),
          3 => 
          array (
            'state' => 'Bihar',
            'districts' => 
            array (
              0 => 'Araria',
              1 => 'Arwal',
              2 => 'Aurangabad',
              3 => 'Banka',
              4 => 'Begusarai',
              5 => 'Bhagalpur',
              6 => 'Bhojpur',
              7 => 'Buxar',
              8 => 'Darbhanga',
              9 => 'East Champaran (Motihari)',
              10 => 'Gaya',
              11 => 'Gopalganj',
              12 => 'Jamui',
              13 => 'Jehanabad',
              14 => 'Kaimur (Bhabua)',
              15 => 'Katihar',
              16 => 'Khagaria',
              17 => 'Kishanganj',
              18 => 'Lakhisarai',
              19 => 'Madhepura',
              20 => 'Madhubani',
              21 => 'Munger (Monghyr)',
              22 => 'Muzaffarpur',
              23 => 'Nalanda',
              24 => 'Nawada',
              25 => 'Patna',
              26 => 'Purnia (Purnea)',
              27 => 'Rohtas',
              28 => 'Saharsa',
              29 => 'Samastipur',
              30 => 'Saran',
              31 => 'Sheikhpura',
              32 => 'Sheohar',
              33 => 'Sitamarhi',
              34 => 'Siwan',
              35 => 'Supaul',
              36 => 'Vaishali',
              37 => 'West Champaran',
            ),
          ),
          4 => 
          array (
            'state' => 'Chandigarh (UT)',
            'districts' => 
            array (
              0 => 'Chandigarh',
            ),
          ),
          5 => 
          array (
            'state' => 'Chhattisgarh',
            'districts' => 
            array (
              0 => 'Balod',
              1 => 'Baloda Bazar',
              2 => 'Balrampur',
              3 => 'Bastar',
              4 => 'Bemetara',
              5 => 'Bijapur',
              6 => 'Bilaspur',
              7 => 'Dantewada (South Bastar)',
              8 => 'Dhamtari',
              9 => 'Durg',
              10 => 'Gariyaband',
              11 => 'Janjgir-Champa',
              12 => 'Jashpur',
              13 => 'Kabirdham (Kawardha)',
              14 => 'Kanker (North Bastar)',
              15 => 'Kondagaon',
              16 => 'Korba',
              17 => 'Korea (Koriya)',
              18 => 'Mahasamund',
              19 => 'Mungeli',
              20 => 'Narayanpur',
              21 => 'Raigarh',
              22 => 'Raipur',
              23 => 'Rajnandgaon',
              24 => 'Sukma',
              25 => 'Surajpur  ',
              26 => 'Surguja',
            ),
          ),
          6 => 
          array (
            'state' => 'Dadra and Nagar Haveli (UT)',
            'districts' => 
            array (
              0 => 'Dadra & Nagar Haveli',
            ),
          ),
          7 => 
          array (
            'state' => 'Daman and Diu (UT)',
            'districts' => 
            array (
              0 => 'Daman',
              1 => 'Diu',
            ),
          ),
          8 => 
          array (
            'state' => 'Delhi (NCT)',
            'districts' => 
            array (
              0 => 'Central Delhi',
              1 => 'East Delhi',
              2 => 'New Delhi',
              3 => 'North Delhi',
              4 => 'North East  Delhi',
              5 => 'North West  Delhi',
              6 => 'Shahdara',
              7 => 'South Delhi',
              8 => 'South East Delhi',
              9 => 'South West  Delhi',
              10 => 'West Delhi',
            ),
          ),
          9 => 
          array (
            'state' => 'Goa',
            'districts' => 
            array (
              0 => 'North Goa',
              1 => 'South Goa',
            ),
          ),
          10 => 
          array (
            'state' => 'Gujarat',
            'districts' => 
            array (
              0 => 'Ahmedabad',
              1 => 'Amreli',
              2 => 'Anand',
              3 => 'Aravalli',
              4 => 'Banaskantha (Palanpur)',
              5 => 'Bharuch',
              6 => 'Bhavnagar',
              7 => 'Botad',
              8 => 'Chhota Udepur',
              9 => 'Dahod',
              10 => 'Dangs (Ahwa)',
              11 => 'Devbhoomi Dwarka',
              12 => 'Gandhinagar',
              13 => 'Gir Somnath',
              14 => 'Jamnagar',
              15 => 'Junagadh',
              16 => 'Kachchh',
              17 => 'Kheda (Nadiad)',
              18 => 'Mahisagar',
              19 => 'Mehsana',
              20 => 'Morbi',
              21 => 'Narmada (Rajpipla)',
              22 => 'Navsari',
              23 => 'Panchmahal (Godhra)',
              24 => 'Patan',
              25 => 'Porbandar',
              26 => 'Rajkot',
              27 => 'Sabarkantha (Himmatnagar)',
              28 => 'Surat',
              29 => 'Surendranagar',
              30 => 'Tapi (Vyara)',
              31 => 'Vadodara',
              32 => 'Valsad',
            ),
          ),
          11 => 
          array (
            'state' => 'Haryana',
            'districts' => 
            array (
              0 => 'Ambala',
              1 => 'Bhiwani',
              2 => 'Charkhi Dadri',
              3 => 'Faridabad',
              4 => 'Fatehabad',
              5 => 'Gurgaon',
              6 => 'Hisar',
              7 => 'Jhajjar',
              8 => 'Jind',
              9 => 'Kaithal',
              10 => 'Karnal',
              11 => 'Kurukshetra',
              12 => 'Mahendragarh',
              13 => 'Mewat',
              14 => 'Palwal',
              15 => 'Panchkula',
              16 => 'Panipat',
              17 => 'Rewari',
              18 => 'Rohtak',
              19 => 'Sirsa',
              20 => 'Sonipat',
              21 => 'Yamunanagar',
            ),
          ),
          12 => 
          array (
            'state' => 'Himachal Pradesh',
            'districts' => 
            array (
              0 => 'Bilaspur',
              1 => 'Chamba',
              2 => 'Hamirpur',
              3 => 'Kangra',
              4 => 'Kinnaur',
              5 => 'Kullu',
              6 => 'Lahaul &amp; Spiti',
              7 => 'Mandi',
              8 => 'Shimla',
              9 => 'Sirmaur (Sirmour)',
              10 => 'Solan',
              11 => 'Una',
            ),
          ),
          13 => 
          array (
            'state' => 'Jammu and Kashmir',
            'districts' => 
            array (
              0 => 'Anantnag',
              1 => 'Bandipore',
              2 => 'Baramulla',
              3 => 'Budgam',
              4 => 'Doda',
              5 => 'Ganderbal',
              6 => 'Jammu',
              7 => 'Kargil',
              8 => 'Kathua',
              9 => 'Kishtwar',
              10 => 'Kulgam',
              11 => 'Kupwara',
              12 => 'Leh',
              13 => 'Poonch',
              14 => 'Pulwama',
              15 => 'Rajouri',
              16 => 'Ramban',
              17 => 'Reasi',
              18 => 'Samba',
              19 => 'Shopian',
              20 => 'Srinagar',
              21 => 'Udhampur',
            ),
          ),
          14 => 
          array (
            'state' => 'Jharkhand',
            'districts' => 
            array (
              0 => 'Bokaro',
              1 => 'Chatra',
              2 => 'Deoghar',
              3 => 'Dhanbad',
              4 => 'Dumka',
              5 => 'East Singhbhum',
              6 => 'Garhwa',
              7 => 'Giridih',
              8 => 'Godda',
              9 => 'Gumla',
              10 => 'Hazaribag',
              11 => 'Jamtara',
              12 => 'Khunti',
              13 => 'Koderma',
              14 => 'Latehar',
              15 => 'Lohardaga',
              16 => 'Pakur',
              17 => 'Palamu',
              18 => 'Ramgarh',
              19 => 'Ranchi',
              20 => 'Sahibganj',
              21 => 'Seraikela-Kharsawan',
              22 => 'Simdega',
              23 => 'West Singhbhum',
            ),
          ),
          15 => 
          array (
            'state' => 'Karnataka',
            'districts' => 
            array (
              0 => 'Bagalkot',
              1 => 'Ballari (Bellary)',
              2 => 'Belagavi (Belgaum)',
              3 => 'Bengaluru (Bangalore) Rural',
              4 => 'Bengaluru (Bangalore) Urban',
              5 => 'Bidar',
              6 => 'Chamarajanagar',
              7 => 'Chikballapur',
              8 => 'Chikkamagaluru (Chikmagalur)',
              9 => 'Chitradurga',
              10 => 'Dakshina Kannada',
              11 => 'Davangere',
              12 => 'Dharwad',
              13 => 'Gadag',
              14 => 'Hassan',
              15 => 'Haveri',
              16 => 'Kalaburagi (Gulbarga)',
              17 => 'Kodagu',
              18 => 'Kolar',
              19 => 'Koppal',
              20 => 'Mandya',
              21 => 'Mysuru (Mysore)',
              22 => 'Raichur',
              23 => 'Ramanagara',
              24 => 'Shivamogga (Shimoga)',
              25 => 'Tumakuru (Tumkur)',
              26 => 'Udupi',
              27 => 'Uttara Kannada (Karwar)',
              28 => 'Vijayapura (Bijapur)',
              29 => 'Yadgir',
            ),
          ),
          16 => 
          array (
            'state' => 'Kerala',
            'districts' => 
            array (
              0 => 'Alappuzha',
              1 => 'Ernakulam',
              2 => 'Idukki',
              3 => 'Kannur',
              4 => 'Kasaragod',
              5 => 'Kollam',
              6 => 'Kottayam',
              7 => 'Kozhikode',
              8 => 'Malappuram',
              9 => 'Palakkad',
              10 => 'Pathanamthitta',
              11 => 'Thiruvananthapuram',
              12 => 'Thrissur',
              13 => 'Wayanad',
            ),
          ),
          17 => 
          array (
            'state' => 'Lakshadweep (UT)',
            'districts' => 
            array (
              0 => 'Agatti',
              1 => 'Amini',
              2 => 'Androth',
              3 => 'Bithra',
              4 => 'Chethlath',
              5 => 'Kavaratti',
              6 => 'Kadmath',
              7 => 'Kalpeni',
              8 => 'Kilthan',
              9 => 'Minicoy',
            ),
          ),
          18 => 
          array (
            'state' => 'Madhya Pradesh',
            'districts' => 
            array (
              0 => 'Agar Malwa',
              1 => 'Alirajpur',
              2 => 'Anuppur',
              3 => 'Ashoknagar',
              4 => 'Balaghat',
              5 => 'Barwani',
              6 => 'Betul',
              7 => 'Bhind',
              8 => 'Bhopal',
              9 => 'Burhanpur',
              10 => 'Chhatarpur',
              11 => 'Chhindwara',
              12 => 'Damoh',
              13 => 'Datia',
              14 => 'Dewas',
              15 => 'Dhar',
              16 => 'Dindori',
              17 => 'Guna',
              18 => 'Gwalior',
              19 => 'Harda',
              20 => 'Hoshangabad',
              21 => 'Indore',
              22 => 'Jabalpur',
              23 => 'Jhabua',
              24 => 'Katni',
              25 => 'Khandwa',
              26 => 'Khargone',
              27 => 'Mandla',
              28 => 'Mandsaur',
              29 => 'Morena',
              30 => 'Narsinghpur',
              31 => 'Neemuch',
              32 => 'Panna',
              33 => 'Raisen',
              34 => 'Rajgarh',
              35 => 'Ratlam',
              36 => 'Rewa',
              37 => 'Sagar',
              38 => 'Satna',
              39 => 'Sehore',
              40 => 'Seoni',
              41 => 'Shahdol',
              42 => 'Shajapur',
              43 => 'Sheopur',
              44 => 'Shivpuri',
              45 => 'Sidhi',
              46 => 'Singrauli',
              47 => 'Tikamgarh',
              48 => 'Ujjain',
              49 => 'Umaria',
              50 => 'Vidisha',
            ),
          ),
          19 => 
          array (
            'state' => 'Maharashtra',
            'districts' => 
            array (
              0 => 'Ahmednagar',
              1 => 'Akola',
              2 => 'Amravati',
              3 => 'Aurangabad',
              4 => 'Beed',
              5 => 'Bhandara',
              6 => 'Buldhana',
              7 => 'Chandrapur',
              8 => 'Dhule',
              9 => 'Gadchiroli',
              10 => 'Gondia',
              11 => 'Hingoli',
              12 => 'Jalgaon',
              13 => 'Jalna',
              14 => 'Kolhapur',
              15 => 'Latur',
              16 => 'Mumbai City',
              17 => 'Mumbai Suburban',
              18 => 'Nagpur',
              19 => 'Nanded',
              20 => 'Nandurbar',
              21 => 'Nashik',
              22 => 'Osmanabad',
              23 => 'Palghar',
              24 => 'Parbhani',
              25 => 'Pune',
              26 => 'Raigad',
              27 => 'Ratnagiri',
              28 => 'Sangli',
              29 => 'Satara',
              30 => 'Sindhudurg',
              31 => 'Solapur',
              32 => 'Thane',
              33 => 'Wardha',
              34 => 'Washim',
              35 => 'Yavatmal',
            ),
          ),
          20 => 
          array (
            'state' => 'Manipur',
            'districts' => 
            array (
              0 => 'Bishnupur',
              1 => 'Chandel',
              2 => 'Churachandpur',
              3 => 'Imphal East',
              4 => 'Imphal West',
              5 => 'Jiribam',
              6 => 'Kakching',
              7 => 'Kamjong',
              8 => 'Kangpokpi',
              9 => 'Noney',
              10 => 'Pherzawl',
              11 => 'Senapati',
              12 => 'Tamenglong',
              13 => 'Tengnoupal',
              14 => 'Thoubal',
              15 => 'Ukhrul',
            ),
          ),
          21 => 
          array (
            'state' => 'Meghalaya',
            'districts' => 
            array (
              0 => 'East Garo Hills',
              1 => 'East Jaintia Hills',
              2 => 'East Khasi Hills',
              3 => 'North Garo Hills',
              4 => 'Ri Bhoi',
              5 => 'South Garo Hills',
              6 => 'South West Garo Hills ',
              7 => 'South West Khasi Hills',
              8 => 'West Garo Hills',
              9 => 'West Jaintia Hills',
              10 => 'West Khasi Hills',
            ),
          ),
          22 => 
          array (
            'state' => 'Mizoram',
            'districts' => 
            array (
              0 => 'Aizawl',
              1 => 'Champhai',
              2 => 'Kolasib',
              3 => 'Lawngtlai',
              4 => 'Lunglei',
              5 => 'Mamit',
              6 => 'Saiha',
              7 => 'Serchhip',
            ),
          ),
          23 => 
          array (
            'state' => 'Nagaland',
            'districts' => 
            array (
              0 => 'Dimapur',
              1 => 'Kiphire',
              2 => 'Kohima',
              3 => 'Longleng',
              4 => 'Mokokchung',
              5 => 'Mon',
              6 => 'Peren',
              7 => 'Phek',
              8 => 'Tuensang',
              9 => 'Wokha',
              10 => 'Zunheboto',
            ),
          ),
          24 => 
          array (
            'state' => 'Odisha',
            'districts' => 
            array (
              0 => 'Angul',
              1 => 'Balangir',
              2 => 'Balasore',
              3 => 'Bargarh',
              4 => 'Bhadrak',
              5 => 'Boudh',
              6 => 'Cuttack',
              7 => 'Deogarh',
              8 => 'Dhenkanal',
              9 => 'Gajapati',
              10 => 'Ganjam',
              11 => 'Jagatsinghapur',
              12 => 'Jajpur',
              13 => 'Jharsuguda',
              14 => 'Kalahandi',
              15 => 'Kandhamal',
              16 => 'Kendrapara',
              17 => 'Kendujhar (Keonjhar)',
              18 => 'Khordha',
              19 => 'Koraput',
              20 => 'Malkangiri',
              21 => 'Mayurbhanj',
              22 => 'Nabarangpur',
              23 => 'Nayagarh',
              24 => 'Nuapada',
              25 => 'Puri',
              26 => 'Rayagada',
              27 => 'Sambalpur',
              28 => 'Sonepur',
              29 => 'Sundargarh',
            ),
          ),
          25 => 
          array (
            'state' => 'Puducherry (UT)',
            'districts' => 
            array (
              0 => 'Karaikal',
              1 => 'Mahe',
              2 => 'Pondicherry',
              3 => 'Yanam',
            ),
          ),
          26 => 
          array (
            'state' => 'Punjab',
            'districts' => 
            array (
              0 => 'Amritsar',
              1 => 'Barnala',
              2 => 'Bathinda',
              3 => 'Faridkot',
              4 => 'Fatehgarh Sahib',
              5 => 'Fazilka',
              6 => 'Ferozepur',
              7 => 'Gurdaspur',
              8 => 'Hoshiarpur',
              9 => 'Jalandhar',
              10 => 'Kapurthala',
              11 => 'Ludhiana',
              12 => 'Mansa',
              13 => 'Moga',
              14 => 'Muktsar',
              15 => 'Nawanshahr (Shahid Bhagat Singh Nagar)',
              16 => 'Pathankot',
              17 => 'Patiala',
              18 => 'Rupnagar',
              19 => 'Sahibzada Ajit Singh Nagar (Mohali)',
              20 => 'Sangrur',
              21 => 'Tarn Taran',
            ),
          ),
          27 => 
          array (
            'state' => 'Rajasthan',
            'districts' => 
            array (
              0 => 'Ajmer',
              1 => 'Alwar',
              2 => 'Banswara',
              3 => 'Baran',
              4 => 'Barmer',
              5 => 'Bharatpur',
              6 => 'Bhilwara',
              7 => 'Bikaner',
              8 => 'Bundi',
              9 => 'Chittorgarh',
              10 => 'Churu',
              11 => 'Dausa',
              12 => 'Dholpur',
              13 => 'Dungarpur',
              14 => 'Hanumangarh',
              15 => 'Jaipur',
              16 => 'Jaisalmer',
              17 => 'Jalore',
              18 => 'Jhalawar',
              19 => 'Jhunjhunu',
              20 => 'Jodhpur',
              21 => 'Karauli',
              22 => 'Kota',
              23 => 'Nagaur',
              24 => 'Pali',
              25 => 'Pratapgarh',
              26 => 'Rajsamand',
              27 => 'Sawai Madhopur',
              28 => 'Sikar',
              29 => 'Sirohi',
              30 => 'Sri Ganganagar',
              31 => 'Tonk',
              32 => 'Udaipur',
            ),
          ),
          28 => 
          array (
            'state' => 'Sikkim',
            'districts' => 
            array (
              0 => 'East Sikkim',
              1 => 'North Sikkim',
              2 => 'South Sikkim',
              3 => 'West Sikkim',
            ),
          ),
          29 => 
          array (
            'state' => 'Tamil Nadu',
            'districts' => 
            array (
              0 => 'Ariyalur',
              1 => 'Chennai',
              2 => 'Coimbatore',
              3 => 'Cuddalore',
              4 => 'Dharmapuri',
              5 => 'Dindigul',
              6 => 'Erode',
              7 => 'Kanchipuram',
              8 => 'Kanyakumari',
              9 => 'Karur',
              10 => 'Krishnagiri',
              11 => 'Madurai',
              12 => 'Nagapattinam',
              13 => 'Namakkal',
              14 => 'Nilgiris',
              15 => 'Perambalur',
              16 => 'Pudukkottai',
              17 => 'Ramanathapuram',
              18 => 'Salem',
              19 => 'Sivaganga',
              20 => 'Thanjavur',
              21 => 'Theni',
              22 => 'Thoothukudi (Tuticorin)',
              23 => 'Tiruchirappalli',
              24 => 'Tirunelveli',
              25 => 'Tiruppur',
              26 => 'Tiruvallur',
              27 => 'Tiruvannamalai',
              28 => 'Tiruvarur',
              29 => 'Vellore',
              30 => 'Viluppuram',
              31 => 'Virudhunagar',
            ),
          ),
          30 => 
          array (
            'state' => 'Telangana',
            'districts' => 
            array (
              0 => 'Adilabad',
              1 => 'Bhadradri Kothagudem',
              2 => 'Hyderabad',
              3 => 'Jagtial',
              4 => 'Jangaon',
              5 => 'Jayashankar Bhoopalpally',
              6 => 'Jogulamba Gadwal',
              7 => 'Kamareddy',
              8 => 'Karimnagar',
              9 => 'Khammam',
              10 => 'Komaram Bheem Asifabad',
              11 => 'Mahabubabad',
              12 => 'Mahabubnagar',
              13 => 'Mancherial',
              14 => 'Medak',
              15 => 'Medchal',
              16 => 'Nagarkurnool',
              17 => 'Nalgonda',
              18 => 'Nirmal',
              19 => 'Nizamabad',
              20 => 'Peddapalli',
              21 => 'Rajanna Sircilla',
              22 => 'Rangareddy',
              23 => 'Sangareddy',
              24 => 'Siddipet',
              25 => 'Suryapet',
              26 => 'Vikarabad',
              27 => 'Wanaparthy',
              28 => 'Warangal (Rural)',
              29 => 'Warangal (Urban)',
              30 => 'Yadadri Bhuvanagiri',
            ),
          ),
          31 => 
          array (
            'state' => 'Tripura',
            'districts' => 
            array (
              0 => 'Dhalai',
              1 => 'Gomati',
              2 => 'Khowai',
              3 => 'North Tripura',
              4 => 'Sepahijala',
              5 => 'South Tripura',
              6 => 'Unakoti',
              7 => 'West Tripura',
            ),
          ),
          32 => 
          array (
            'state' => 'Uttarakhand',
            'districts' => 
            array (
              0 => 'Almora',
              1 => 'Bageshwar',
              2 => 'Chamoli',
              3 => 'Champawat',
              4 => 'Dehradun',
              5 => 'Haridwar',
              6 => 'Nainital',
              7 => 'Pauri Garhwal',
              8 => 'Pithoragarh',
              9 => 'Rudraprayag',
              10 => 'Tehri Garhwal',
              11 => 'Udham Singh Nagar',
              12 => 'Uttarkashi',
            ),
          ),
          33 => 
          array (
            'state' => 'Uttar Pradesh',
            'districts' => 
            array (
              0 => 'Agra',
              1 => 'Aligarh',
              2 => 'Allahabad',
              3 => 'Ambedkar Nagar',
              4 => 'Amethi (Chatrapati Sahuji Mahraj Nagar)',
              5 => 'Amroha (J.P. Nagar)',
              6 => 'Auraiya',
              7 => 'Azamgarh',
              8 => 'Baghpat',
              9 => 'Bahraich',
              10 => 'Ballia',
              11 => 'Balrampur',
              12 => 'Banda',
              13 => 'Barabanki',
              14 => 'Bareilly',
              15 => 'Basti',
              16 => 'Bhadohi',
              17 => 'Bijnor',
              18 => 'Budaun',
              19 => 'Bulandshahr',
              20 => 'Chandauli',
              21 => 'Chitrakoot',
              22 => 'Deoria',
              23 => 'Etah',
              24 => 'Etawah',
              25 => 'Faizabad',
              26 => 'Farrukhabad',
              27 => 'Fatehpur',
              28 => 'Firozabad',
              29 => 'Gautam Buddha Nagar',
              30 => 'Ghaziabad',
              31 => 'Ghazipur',
              32 => 'Gonda',
              33 => 'Gorakhpur',
              34 => 'Hamirpur',
              35 => 'Hapur (Panchsheel Nagar)',
              36 => 'Hardoi',
              37 => 'Hathras',
              38 => 'Jalaun',
              39 => 'Jaunpur',
              40 => 'Jhansi',
              41 => 'Kannauj',
              42 => 'Kanpur Dehat',
              43 => 'Kanpur Nagar',
              44 => 'Kanshiram Nagar (Kasganj)',
              45 => 'Kaushambi',
              46 => 'Kushinagar (Padrauna)',
              47 => 'Lakhimpur - Kheri',
              48 => 'Lalitpur',
              49 => 'Lucknow',
              50 => 'Maharajganj',
              51 => 'Mahoba',
              52 => 'Mainpuri',
              53 => 'Mathura',
              54 => 'Mau',
              55 => 'Meerut',
              56 => 'Mirzapur',
              57 => 'Moradabad',
              58 => 'Muzaffarnagar',
              59 => 'Pilibhit',
              60 => 'Pratapgarh',
              61 => 'RaeBareli',
              62 => 'Rampur',
              63 => 'Saharanpur',
              64 => 'Sambhal (Bhim Nagar)',
              65 => 'Sant Kabir Nagar',
              66 => 'Shahjahanpur',
              67 => 'Shamali (Prabuddh Nagar)',
              68 => 'Shravasti',
              69 => 'Siddharth Nagar',
              70 => 'Sitapur',
              71 => 'Sonbhadra',
              72 => 'Sultanpur',
              73 => 'Unnao',
              74 => 'Varanasi',
            ),
          ),
          34 => 
          array (
            'state' => 'West Bengal',
            'districts' => 
            array (
              0 => 'Alipurduar',
              1 => 'Bankura',
              2 => 'Birbhum',
              3 => 'Burdwan (Bardhaman)',
              4 => 'Cooch Behar',
              5 => 'Dakshin Dinajpur (South Dinajpur)',
              6 => 'Darjeeling',
              7 => 'Hooghly',
              8 => 'Howrah',
              9 => 'Jalpaiguri',
              10 => 'Kalimpong',
              11 => 'Kolkata',
              12 => 'Malda',
              13 => 'Murshidabad',
              14 => 'Nadia',
              15 => 'North 24 Parganas',
              16 => 'Paschim Medinipur (West Medinipur)',
              17 => 'Purba Medinipur (East Medinipur)',
              18 => 'Purulia',
              19 => 'South 24 Parganas',
              20 => 'Uttar Dinajpur (North Dinajpur)',
            ),
          ),
       
    );

    foreach ($states as $key => $value) {
            print_r($value['districts']);
    }
}

}

// 'states' => 
//         array (
//           0 => 
//           array (
//             'state' => 'Andhra Pradesh',
//             'districts' => 
//             array (
//               0 => 'Anantapur',